---
title: "Prioritzr_dry_run_1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(prioritizr)
library(here)
library(tidyverse)

```

```{r}
# load raster planning unit data
pu <- here("rasters", "mz_id.tif")
pu_rast <-  raster(pu)

print(pu_rast)

plot(pu_rast)
```

```{r}
#load artisanal fisheries raster
fishing_tif <- here("rasters", "fishing.tif")

fishing_raster <- raster(fishing_tif)

fishing_df <- as.data.frame(fishing_raster)

#scale all values 0-1 by dividing by max value using log-transformed +1 fishing values (+1 so that zero values are transformed to zero not NA)
fishing<- log(fishing_raster+1)/cellStats(log(fishing_raster+1), max)

cost <- fishing
```

```{r}
# load feature data - for some reason this one is not working - here("rasters", "species", "species_Fis-23071.tif")

features_stack = stack(here("rasters", "multilayer_feature.tif"), here("rasters", "species", "species_Fis-31568.tif"),  here("rasters", "species", "species_Fis-23898.tif"), here("rasters", "species", "species_Fis-23899.tif"), here("rasters", "species", "species_Fis-23061.tif"), here("rasters", "species", "species_Fis-23064.tif"), here("rasters", "species", "species_Fis-58485.tif"), here("rasters", "species", "species_Fis-29423.tif"), here("rasters", "species", "species_Fis-29388.tif"), here("rasters", "species", "species_Fis-30583.tif"), here("rasters", "species", "species_Fis-23273.tif"), here("rasters", "species", "species_Fis-23274.tif"), here("rasters", "species", "species_Fis-23277.tif"), here("rasters", "species", "species_Fis-8339.tif"), here("rasters", "species", "species_Fis-47352.tif"), here("rasters", "species", "species_Fis-24098.tif"), here("rasters", "species", "species_Fis-163295.tif"), here("rasters", "species", "species_Fis-61508.tif"), here("rasters", "species", "species_Fis-30521.tif"), here("rasters", "species", "species_Fis-32599.tif"), here("rasters", "species", "species_Fis-131821.tif"), here("rasters", "species", "species_Fis-32975.tif"))

con_features_df <- as.data.frame(features_stack)

```

```{r}
#lets load in existing MPA's to lockin to the design and oil rigs to lock out

mpa_tif <- (here("rasters", "mpa.tif")) 
mpa_raster <- raster(mpa_tif) 

mpa_df <- as.data.frame(mpa_raster)
```


```{r}
#lets load in oil to lock out of design
oil_tif <- (here("rasters", "oil.tif")) 
oil_raster <- raster(oil_tif) 

oil_df <- as.data.frame(oil_raster)
```

LET'S MAKE SOME PROBLEMS
```{r}
# SCENARIO 1: Minimize Fishing Cost while meeting 20% representation targets, locking in MPAs, and locking out oil rigs

prob <- problem(cost, features = features_stack) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2) %>%
  add_locked_in_constraints(mpa_raster) %>%
  add_locked_out_constraints(oil_raster)

sprob<- solve(prob) 

plot(sprob,  main ="Fishing Pressure - 20% Target w MPAs")

```



```{r}
## SENSITIVTY ANALSYSIS TEST 1: nothing locked in or out
# Minimize Fishing Cost while meeting 20% representation targets, without locking in MPAs, and locking out oil rigs

prob_no_mpas <- problem(cost, features = features_stack) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2)

print(prob_no_mpas)

#solve problem
sprob_no_mpas <- solve(prob_no_mpas)

plot(sprob_no_mpas,  main = c("Sensitivty Analyis:Fishing Pressure - 20% Targets"))
```

```{r}
## SENSITIVTY ANALSYSIS TEST 2: 50% Targets
# Minimize Fishing Cost while meeting 50% representation targets,  locking in MPAs, and locking out oil rigs

prob_50<- problem(cost, features = features_stack) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.5) %>%
  add_locked_in_constraints(mpa_raster) %>%
  add_locked_out_constraints(oil_raster)

sprob_50<- solve(prob_50)

plot(sprob_50,  main ="Fishing Pressure - 50% Target w MPAs")

```
```{r}
## SENSITIVTY ANALSYSIS TEST 3: boundary length modifier
# Minimize Fishing Cost while meeting 20% representation targets, without locking in MPAs, and locking out oil rigs

prob_blm <- problem(cost, features = features_stack) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2) %>%
  add_boundary_penalties(0.1)

print(prob_blm)

#solve problem
sprob_blm <- solve(prob_blm)

plot(sprob_blm,  main = c("Sensitivty Analyis:Fishing Pressure - 20% Targets"))
```
```

