---
title: "Cost 1 - Proximity to Ports"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load libraries
library(raster)
library(tidyverse)
library(here)
library(sf)
library(fasterize)
```

```{r}
# set up path to port data
ports_path <- 'G:/group_project/data/moz_ports/moz_ports'
ports_shape <- list.files(ports_path, full.names = TRUE)

## Get MZ EEZ tif file
mz_rast_id <- raster(here("rasters/mz_id.tif"))

# read in shapefile from path
ports_sf <- sf::read_sf(ports_shape[6])
class(ports_sf) 

# check crs
st_crs(ports_sf)

# it is in generic lat-long, 4326 so we need to transform it to the Mozambique CRS
ports_sf <- ports_sf %>%
  st_transform(crs = st_crs(mz_rast_id))

ports_sp <- as(ports_sf, 'Spatial')

class(ports_sp)
### [1] "SpatialPointsDataFrame"
### attr(,"package")
### [1] "sp"
crs(ports_sp)

ports_rast <- raster::rasterize(ports_sp, mz_rast_id, field = 'OBJECTID_1')
plot(ports_rast)
```

```{r}
# take ports raster and creating distance to ports raster
port_dist_rast <- raster::distanceFromPoints(mz_rast_id, ports_sp)
plot(port_dist_rast)

# mask it to be only within the EEZ
port_dist_rast <- port_dist_rast %>% mask(mz_eez_buffer_sf)
plot(port_dist_rast)

# write as a tif file
writeRaster(port_dist_rast, here('rasters/port_dist_rast.tif'), overwrite = TRUE)


```

