---
title: "5_dry_run_ports"
author: "Rachel Rhodes"
date: "12/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(prioritizr)
library(here)
library(tidyverse)
```

```{r}
# Assuming we have run script 4 already some of these variables will be in the environment

# we will want to load a new cost layer though
port_tif <- here("rasters", "port_dist_rast.tif")

port_raster <- raster(port_tif)

##you can also do this shortcut:) 
##port_raster <- raster(here("rasters/port_dist_rast.tif"))

plot(port_raster)

port_df <- as.data.frame(port_raster)

#scale all values 0-1 by dividing by max value using log-transformed +1 ports values (+1 so that zero values are transformed to zero not NA)
ports<- log(port_raster+1)/ cellStats(log(port_raster+1), max)

plot(ports)

cost_ports <- ports
```
```{r}
# SCENARIO 1: Minimize ara while meeting 20% representation targets, locking in MPAs, and locking out oil rigs

prob_ports <- problem(cost_ports, features = features_stack) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2) %>%
  add_locked_in_constraints(mpa_raster) %>% 
  add_locked_out_constraints(oil_raster)

print(prob_ports)

#solve problem
sprob_ports <- solve(prob_ports)

plot(sprob_ports,  main = c("Ports - 20% Targets"))

```

```{r}
## SENSITIVTY ANALSYSIS TEST 1: nothing locked in or out
# Minimize Fishing Area while meeting 20% representation targets, without locking in MPAs, and locking out oil rigs

ports_20 <- problem(cost_ports, features = features_stack) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2)
  

print(ports_20)

#solve problem
sprob_ports_20 <- solve(ports_20)

plot(sprob_ports_20,  main = c("Ports - 20% Targets"))

```


```{r}
## SENSITIVTY ANALSYSIS TEST 2: 50% Targets
# Minimize Fishing Cost while meeting 50% representation targets,  locking in MPAs, and locking out oil rigs

ports_50 <- problem(cost_ports, features = features_stack) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.5) %>% 
  add_locked_in_constraints(mpa_raster) %>% 
  add_locked_out_constraints(oil_raster)
  

print(ports_50)

#solve problem
sprob_ports_50 <- solve(ports_50)

plot(sprob_ports_50,  main = c("Ports - 50% Targets"))

```

```{r}
## SENSITIVTY ANALSYSIS TEST 3: No BLM
# Minimize Fishing Cost while meeting 20% representation targets, without locking in MPAs, and locking out oil rigs

prob_area_no_blm <- problem(cost, features = features_stack) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2) %>%
  add_gurobi_solver(gap=0.1)

print(prob_area_no_blm)

#solve problem
sprob_area_no_blm <- solve(prob_area_no_blm)

plot(sprob_area_no_blm,  main = c("Sensitivty Analyis:Fishing Pressure - 20% Targets"))

#writeRaster(sprob_area_blm, here('outputs/area_blm_10.tif'), overwrite = TRUE)
```

