---
title: "Area"
author: "Rachel Rhodes"
date: "12/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(prioritizr)
library(here)
library(tidyverse)
```

```{r}
## Assuming we have run script 4 already some of these variable will be in the environment

# we will want to load a new cost layer though using distance
area_tif <- here("rasters", "mz_id.tif")

area_raster <- raster(area_tif)
values(area_raster) <- 0.5

# make a data frame to check values
area_df <- as.data.frame(area_raster)

# set cost to area raster
cost_area <- area_raster

```



```{r}
# SCENARIO 1: Minimize ara while meeting 20% representation targets, locking in MPAs, and locking out oil rigs, with optimal boundary penalty

prob_area <- problem(cost_area, features = features_stack) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2) %>%
  add_locked_in_constraints(mpa_raster) %>%
  add_locked_out_constraints(oil_raster) %>%
  add_boundary_penalties(630) %>%
  add_gurobi_solver(gap=1.02)
  

print(prob_area)

#solve problem
sprob_area <- solve(prob_area)

plot(sprob_area,  main = c("Area - 20% Targets"))

#Optimal solution found (tolerance 1.00e-01) Best objective 6.365000000000e+02, best bound 6.300000000000e+02, gap 1.0212%
```

```{r}
## SENSITIVTY ANALSYSIS TEST 1: nothing locked in or out
# Minimize Fishing Area while meeting 20% representation targets, without locking in MPAs, and locking out oil rigs

prob_area_no_mpas <- problem(cost, features = features_stack) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2)

print(prob_area_no_mpas)

#solve problem
sprob_area_no_mpas <- solve(prob_area_no_mpas)

plot(sprob_area_no_mpas,  main = c("Sensitivty Analyis: Min Area with no MPAs"))
```

```{r}
## SENSITIVTY ANALSYSIS TEST 2: 50% Targets
# Minimize Fishing Cost while meeting 50% representation targets,  locking in MPAs, and locking out oil rigs

prob_area_50<- problem(cost, features = features_stack) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.5) %>%
  add_locked_in_constraints(mpa_raster) %>%
  add_locked_out_constraints(oil_raster)

sprob_area_50<- solve(prob_area_50)

plot(sprob_area_50,  main ="Area - 50% Target w MPAs")
```

```{r}
## SENSITIVTY ANALSYSIS TEST 3: No BLM
# Minimize Fishing Cost while meeting 20% representation targets, without locking in MPAs, and locking out oil rigs

prob_area_no_blm <- problem(cost, features = features_stack) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.2) %>%
  add_gurobi_solver(gap=0.1)

print(prob_area_no_blm)

#solve problem
sprob_area_no_blm <- solve(prob_area_no_blm)

plot(sprob_area_no_blm,  main = c("Sensitivty Analyis:Fishing Pressure - 20% Targets"))

#writeRaster(sprob_area_blm, here('outputs/area_blm_10.tif'), overwrite = TRUE)

```

