---
title: "Prioritzr_dry_run_1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(prioritizr)
```

```{r}
# load raster planning unit data
pu <- here("rasters", "mz_id.tif")
pu_rast <-  raster(pu)

print(pu_rast)

plot(pu_rast)
```

```{r}
fishing_tif <- here("rasters", "fishing.tif")

fishing_raster <- raster(fishing_tif)

plot(fishing_raster)

fishing_df <- as.data.frame(fishing_raster)

fishing<- log(fishing_raster+1)/ cellStats(log(fishing_raster+1), max)

plot(fishing)

cost <- fishing
```

```{r}
# load feature data
features_stack = stack(here("rasters", "multilayer_feature.tif"))

con_features_df <- as.data.frame(features_stack)

```

```{r}
# create problem
prob <- problem(cost, features = features_stack) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.3)

print(problem)

#solve problem
sprob <- solve(prob)

plot(sprob,  main = c("30% of 7 habitats, 50% species richness (interpolated), penalty = 0.001, edge = 0.5"))
```

```{r}
# lets load in existing MPA's to lockin to the design

mpa_tif <- (here("rasters", "mpa.tif")) 
mpa_raster <- raster(mpa_tif) 

plot(mpa_raster)

mpa_df <- as.data.frame(mpa_raster)
```

```{r}
# Create second conservation problem to protect 30% of each habitat while minimizing cost/overal with fishing effort porxy with areas selected as existing marine protected areas in the reserve design results

prob_with_lock_in <- prob %>% add_locked_in_constraints(mpa_raster)
```

