---
title: "Species"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(tidyverse)
library(sf)
library(here)
library(fasterize)
```

```{r}
# read in MZ EEZ tif
mz_rast <- raster(here("rasters", "mz_id.tif"))

# read in aquamaps csv file
hcaf_df <- read_csv(here("data", "am_hcaf.csv"))

#create an xyz dataframe for the raster::rasterFromXYZ function
xyz_df <- hcaf_df %>%
  select(x = center_long, y = center_lat, z = loiczid)

hcaf_rast <- raster::rasterFromXYZ(xyz_df)

crs(hcaf_rast) <- '+init=epsg:4326'

hcaf_reproj <- raster::projectRaster(hcaf_rast, res = 10000,
                                            method = 'ngb',
                                            crs = crs(mz_rast))

hcaf_mz_rast <- raster::crop(hcaf_reproj, mz_rast)

```


```{r}
# read in aquamaps data
mz <- read_csv(here("data","moz_spp_native.csv"))

# read in info about species in aquamaps dta
mz_info <- read_csv(here("data","moz_spp_info.csv"))
```

```{r}
#filter using the top 30 species id
mz_snr_species <- mz %>% 
  filter(am_sid %in% c("Fis-31568",
                       "Fis-23898",
                       "Fis-23899",
                       "Fis-23061",
                       "Fis-23064",
                       "Fis-23071", 
                       "Fis-58485",
                       "Fis-29423",
                       "Fis-29388",
                       "Fis-30583",
                       "Fis-23273",
                       "Fis-23274",
                       "Fis-23277", 
                       "Fis-8339",
                       "Fis-47352",
                       "Fis-24098",
                       "Fis-163295",
                       "Fis-61508",
                       "Fis-30521",
                       "Fis-32599",
                       "Fis-131821",
                       "Fis-32975"))
```

```{r}
# Species 1- Hammerhead
hh_id <- 'Fis-23273'
hh_cells_df <- mz %>%
  filter(am_sid == hh_id)

### use raster::subs() to substitute in values for others
hh_range_rast <- subs(hcaf_mz_rast, hh_cells_df,
                      by = 'loiczid', ### which variable is the key
                      which = 'prob') %>% 
  trim()### which var is the new value
plot(hh_range_rast)

species_23273 <- writeRaster(hh_range_rast, here("rasters", "species_23273.tif"), overwrite = T)

```

```{r}
# Species 2 - Pelagic thresher
th_id <- 'Fis-31568'
th_cells_df <- mz %>%
  filter(am_sid == th_id)

### use raster::subs() to substitute in values for others
th_range_rast <- subs(hcaf_mz_rast, th_cells_df,
                      by = 'loiczid', ### which variable is the key
                      which = 'prob') %>% 
  trim()### which var is the new value
plot(th_range_rast)

writeRaster(hh_range_rast, here("rasters", "species_31568.tif"), overwrite = T)

```


```{r}
# Species 3 - Bigeye thresher
bt_id <- 'Fis-23898'
bt_cells_df <- mz %>%
  filter(am_sid == bt_id)

### use raster::subs() to substitute in values for others
bt_range_rast <- subs(hcaf_mz_rast, bt_cells_df,
                      by = 'loiczid', ### which variable is the key
                      which = 'prob') %>% 
  trim()### which var is the new value
plot(bt_range_rast)

writeRaster(bt_range_rast, here("rasters", "species_23898.tif"), overwrite = T)

```
```{r}
# Species 4 - Thresher
thresh_id <- 'Fis-23899'
thresh_cells_df <- mz %>%
  filter(am_sid == thresh_id)

### use raster::subs() to substitute in values for others
thresh_range_rast <- subs(hcaf_mz_rast, thresh_cells_df,
                      by = 'loiczid', ### which variable is the key
                      which = 'prob') %>% 
  trim()### which var is the new value
plot(thresh_range_rast)

writeRaster(thresh_range_rast, here("rasters", "species_23899.tif"), overwrite = T)

```
```{r}

# Species 5 - Oceanic whitetip shark
oceanic_id <- 'Fis-23061'
oceanic_cells_df <- mz %>%
  filter(am_sid == oceanic_id)

### use raster::subs() to substitute in values for others
oceanic_range_rast <- subs(hcaf_mz_rast, oceanic_cells_df,
                      by = 'loiczid', ### which variable is the key
                      which = 'prob') %>% 
  trim()### which var is the new value
plot(oceanic_range_rast)

writeRaster(oceanic_range_rast, here("rasters", "species_23061.tif"), overwrite = T)


```

